version: '3.8'

services:
  tms:
    container_name: TMS
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${username}
      - SPRING_DATASOURCE_PASSWORD=${password}
      - SPRING_DATASOURCE_USERNAME=${username}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=8082
    ports:
      - '8081:8082'

  db:
    container_name: db
    image: postgres
    environment:
    - POSTGRES_PASSWORD=${password}
    - POSTGRES_USER=${username}
    ports:
      - '5432:5432'


