version: '3.8'

services:
  tms:
    container_name: TMS
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  db:
    container_name: post
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
    ports:
      - "5432"
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)